import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import './Project.css';
function Projects() {
    const [selected, setSelected] = useState(null);
    const projects = [
        { id: 1, name: 'JARVIS', tag: 'AI · RESTAURANT SAAS', shortDesc: 'AI-powered restaurant operating system connecting ordering, kitchen workflows, analytics and business intelligence.', longDesc: 'A multi-tenant restaurant operations product built around the full order lifecycle. Customers can order through touch, voice or table QR; orders move into a live kitchen workflow; operators manage menus, modifiers, stock and profitability; and an AI Operations Agent can answer questions using restaurant data.', role: 'Full-Stack & AI Developer', tech: ['React', 'FastAPI', 'PostgreSQL', 'AI / LLM', 'WebSockets'], image: '/projects/jarvis.png', highlights: ['AI voice + touch ordering', 'Live Kitchen Display System', 'QR ordering & KOT workflows', 'Analytics + AI Operations Agent'] },
        { id: 2, name: 'CEFRise', tag: 'EDTECH · MOBILE', shortDesc: 'A CEFR-based English vocabulary learning app combining structured learning, pronunciation, visuals and assessment.', longDesc: 'A mobile learning product designed around CEFR proficiency levels. It combines structured vocabulary, pronunciation audio, visual word references, collocations and interactive practice, with onboarding assessment to personalize the learning journey.', role: 'Flutter Developer', tech: ['Flutter', 'Firebase', 'Supabase', 'Dart'], image: '/projects/cefrise.png', highlights: ['CEFR vocabulary learning', 'Pronunciation & visual references', 'Onboarding level assessment', 'Cloud data & media storage'] },
        { id: 3, name: 'Preventive Maintenance System', tag: 'ENTERPRISE · COMPLIANCE', shortDesc: 'A full-stack maintenance and compliance platform for inspections, non-compliance workflows and operational reporting.', longDesc: 'An internal business system that digitizes the preventive maintenance lifecycle — from scheduled surveys and compliance assessment to non-compliance tracking, corrective actions, evidence, review, closure and reporting. The interface provides clear operational visibility while role-based workflows keep responsibilities controlled.', role: 'Full-Stack Developer', tech: ['Laravel', 'PHP', 'React', 'PostgreSQL'], image: '/projects/preventive.png', highlights: ['Scheduled survey lifecycle', 'Compliance & issue tracking', 'Corrective-action workflows', 'Role-based access & analytics'] }
    ];
    return <section className="projects-section" id="projects"><div className="neon-orb-blue" /><div className="neon-orb-violet" /><motion.div className="projects-container" initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .08 }}><p className="eyebrow">Selected Work</p><h2 className="projects-headline">Real products. Real workflows. Designed and engineered end to end.</h2><p className="projects-intro">A selection of products across AI SaaS, mobile learning and enterprise operations. Click any project to explore the thinking behind it.</p><div className="magazine-project-grid">{projects.map((p, i) => <motion.article className={`mag-card slot-${i + 1}`} key={p.id} whileHover={{ y: -10, scale: 1.008 }} onClick={() => setSelected(p)}><div className="glass-shine-layer" /><div className="mag-card-header"><span className="mag-tag">{p.tag}</span><span className="mag-year">0{i + 1}</span></div><div className="mag-visual-wrapper"><img className="project-visual-media" src={p.image} alt={`${p.name} product visual`} /></div><div className="mag-card-body"><h3 className="mag-title">{p.name}</h3><p className="mag-desc">{p.shortDesc}</p><div className="project-mini-stack">{p.tech.slice(0, 4).map(t => <span key={t}>{t}</span>)}</div></div><div className="mag-card-footer"><span className="mag-action-text">Explore Case Study</span><div className="mag-btn-circle">↗</div></div></motion.article>)}</div></motion.div>
        <AnimatePresence>{selected && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelected(null)}><motion.div className="detailed-glass-panel" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', damping: 25, stiffness: 180 }} onClick={e => e.stopPropagation()}><button className="close-panel-btn" onClick={() => setSelected(null)}>×</button><div className="panel-hero-visual"><img src={selected.image} alt={selected.name} /></div><span className="panel-tag">{selected.tag}</span><h2 className="panel-title">{selected.name}</h2><div className="panel-meta-row"><div><span>My Role</span><p>{selected.role}</p></div><div><span>Project Type</span><p>{selected.tag.split('·')[0]}</p></div></div><hr className="panel-divider" /><div className="panel-body"><h3>What I built</h3><p>{selected.longDesc}</p><h3>Core capabilities</h3><div className="case-highlight-grid">{selected.highlights.map(h => <div key={h}>✓ {h}</div>)}</div><h3>Technology</h3><div className="panel-tech-wrap">{selected.tech.map(t => <span key={t} className="panel-tech-pill">{t}</span>)}</div><p className="case-note">Public portfolio presentation uses non-sensitive product information only. Internal URLs, credentials and operational data are intentionally excluded.</p></div></motion.div></motion.div>}</AnimatePresence>
    </section>
}
export default Projects;
